### ISSUE TITLE
Experiencing Slow ArrayPool Performance with Enumerables

### ISSUE THREAD

**Issue by Mike-E-angelo** [NetFabric/NetFabric.Hyperlinq#373]
Please see the SLN found here:

https://github.com/Mike-E-angelo/Stash/tree/master/Hyperlinq.Memory

When running the tests, I see the following:

```
|              Method |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |----------:|---------:|---------:|-------:|------:|------:|----------:|
|      LinqEnumerable |  28.76 ns | 0.242 ns | 0.226 ns | 0.0038 |     - |     - |      32 B |
| HyperlinqEnumerable | 164.11 ns | 3.246 ns | 4.656 ns | 0.0038 |     - |     - |      32 B |
|     BasicEnumerable |  64.24 ns | 1.303 ns | 1.219 ns | 0.0038 |     - |     - |      32 B |
|           LinqArray |  30.62 ns | 0.479 ns | 0.400 ns | 0.0038 |     - |     - |      32 B |
|      HyperlinqArray |  44.31 ns | 0.663 ns | 0.620 ns |      - |     - |     - |         - |
|          BasicArray |  66.51 ns | 0.699 ns | 0.620 ns | 0.0038 |     - |     - |      32 B |

```

You can see that `HyperlinqEnumerable` seems abnormally slow.  It is a copy/paste of `HyperlinqArray` but uses an `IEnumerable<int>` instead of an `int[]`.

Wanted to bring this up in case it's not a known issue.  Or if I have something fundamentally misunderstood. :)

**Comment by Mike-E-angelo** [comment]
This might be related.  [I added a new benchmark](https://github.com/Mike-E-angelo/Stash/blob/master/Hyperlinq.Memory/Hyperlinq.Memory/ContainsBenchmarks.cs) where it appears that the enumerable `Contains` incurs some allocations:

```
// * Summary *

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1110 (21H1/May2021Update)
AMD Ryzen 7 3700X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.100-preview.6.21355.2
  [Host]     : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT


|              Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
|           LinqArray | 13.34 ns | 0.144 ns | 0.135 ns |      - |     - |     - |         - |
|      HyperlinqArray | 10.40 ns | 0.176 ns | 0.147 ns |      - |     - |     - |         - |
|      LinqEnumerable | 13.35 ns | 0.199 ns | 0.177 ns |      - |     - |     - |         - |
| HyperlinqEnumerable | 29.81 ns | 0.609 ns | 0.834 ns | 0.0038 |     - |     - |      32 B |
```

**Comment by aalmada** [comment]
Sorry, I didn't notice you reported an issue. 😦
I'll have to check what's going on.
Thanks for reporting it.

**Comment by Mike-E-angelo** [comment]
Hah!  No worries.  Better late than never. 😁

I also reported #372 FWIW. 😇

**Comment by aalmada** [comment]
> I took another look at the `Contains`. I understand you are saying it can be boxed, but I guess I am confused on how Linq can be so much faster without any additional allocations. It almost suggests to do a check for `IEnumerable` and if so use Linq instead of Hyperlinq.

Yes, you're right. That shouldn't happen. I now understand that it's an issue with how `AsValueEnumerable()` is implemented. 

I've been working on a total refactor of the source generator that will fix this issue and many more. I hope to release this other version soon.

> > The issue is that, even if I calculate the sum for both, the dispose is still accounted for
> 
> I believe I am following with everything except this. You mean _unaccounted for_, correct? From my understanding Dispose is not being called, thus the disparity.
> 
> In any case, there is still a huge disparity with the `HyperlinqEnumerable` and everything else. It again makes me wonder if we can ascertain that it's strictly `IEnumerable` (and not `ICollection`, etc) to use Linq and Hyperlinq for everything else.

![image](https://user-images.githubusercontent.com/534533/131233010-fc9f2f55-9df5-4a61-9bd5-9312b86c9a9e.png)

Those 10x times slower can't be the disposing. 🤪  I'm going to check what's going on.

**Comment by aalmada** [comment]
Ok! Now I remember why `ToArray()` is a lot slower when passing an `ArrayPool` and the source implements `ICollection<>`.

Both implementations of `ToArray()` need to allocate or rent the memory space, then copy the contents of the enumerable into it. 

If the source implements `ICollection<T>`, then `CopyTo(T[], int)` should be used instead. It can use memory copy APIs instead of enumerating the collection. The issue is that this method takes an array as the source (first parameter). The `ArrayPool.Rent()` methods returns a `Span<>` not an array. There's no `CopyTo()` for `Span<>` so, the source has to be enumerated using its `IEnumerable<>` implementation, which is usually much slower... 😞

Unfortunately `Span<>`is still not prevalent throughout all APIs...

**Comment by Mike-E-angelo** [comment]
> If the source implements ICollection<T>, then CopyTo(T[], int) should be used instead

OK thank you for the investigation/explanation @aalmada ... If I understand correctly, the `CopyTo` is what is occurring in Linq and not Hyperlinq, correct?  Is this something you think will be done in the new source generator magic you're working on?

> The ArrayPool.Rent() methods returns a Span<> not an array

To clarify here, I believe you meant the inverse. 😁   That is, `ArrayPool.Rent()` returns an array and not a `Span`.  The rest does align with my understanding, there is no `CopyTo(Span<>)` and the closest that I know of is `CollectionsMarshal.AsSpan` which only deals with `List<T>`.

**Comment by aalmada** [comment]
> > If the source implements ICollection, then CopyTo(T[], int) should be used instead
> 
> OK thank you for the investigation/explanation @aalmada ... If I understand correctly, the `CopyTo` is what is occurring in Linq and not Hyperlinq, correct? Is this something you think will be done in the new source generator magic you're working on?
> 

Right, `CopyTo` is occurring in Linq but not Hyperlinq. It's not related to the source generator. It's only related to the limitation on the `CopyTo` destination parameter but read what's next... 

> > The ArrayPool.Rent() methods returns a Span<> not an array
> 
> To clarify here, I believe you meant the inverse. 😁 That is, `ArrayPool.Rent()` returns an array and not a `Span`. The rest does align with my understanding, there is no `CopyTo(Span<>)` and the closest that I know of is `CollectionsMarshal.AsSpan` which only deals with `List<T>`.

Damnit, you're right once again. I feel so embarrassed... 😔

`ArrayPool.Rent()` does return an array. It's my implementation of `ValueMemoryOwner<>` that returns `Memory<>`. 

I implemented it this way because `ArrayPool.Rent()` may return an array larger than requested. That requires some more work by the caller of `ToArray()` if this larger array was returned. I slice it using a `Memory<>` to make it simpler. I implement `IMemoryOwner<>` to make it similar to `MemoryPool`.

Sorry, I got lost in these details and forgot about the return type of `ArrayPool.Rent()`.

This means I can fix the issue. `CopyTo` can be applied on the unsliced array and then return the sliced one.

Thanks for insisting on this... 😞

**Comment by Mike-E-angelo** [comment]
> Sorry, I got lost in these details and forgot about the return type of ArrayPool.Rent().

Hah no worries there are only a million billion things going on with what we do here. :)  I am amazed that I am able to keep as many details straight that I do, personally.  It's sort of the name of the game, TBH.  And FWIW my intent is not to point out that a possible mistake was made (an attitude that seems to be rampant in dev culture) but to ensure my understanding and that I am following along correctly.

In any case, I am glad you are able to apply a fix. 👍

**Comment by aalmada** [comment]
Much more acceptable 
![image](https://user-images.githubusercontent.com/534533/131386914-963ac875-0501-4a2d-aff9-5b0ea6c53801.png)

**Comment by Mike-E-angelo** [comment]
Cool I do see some improvements, nice work!  Although to be sure, `Enumerable_Reference_ArrayPool` seems like it's regressed from 33% to 85% slower. :S

**Comment by aalmada** [comment]
Today I was thinking a bit more about `Contains()` and realized I don't need the source generator to fix the issue with your case.

`Contains()` is very confusing because it's both a LINQ method and an `ICollection<>` method. I have to be very careful not to create infinite call loops. I have already written so many versions of it that I lost count. I sure hope this is the last time.  😉

`Contains()`

![image](https://user-images.githubusercontent.com/534533/131583467-f9700110-2c32-4fdb-ae10-6239f9b976a6.png)

`ToArray()` performance is about the same with and without `ArrayPool`.

![image](https://user-images.githubusercontent.com/534533/131584620-c58190c2-4bef-49e2-839d-1e5ab9a7fa20.png)

**Comment by Mike-E-angelo** [comment]
Awesome!  Thank you for your efforts, @aalmada!
